# Knowledge Base for Anime Recommendation Expert System (Sistem Pakar Rekomendasi Anime)

ANIME_DB = [
    {
        "id": 1,
        "title": "Attack on Titan",
        "genre": ["action", "drama", "fantasy", "mystery"],
        "type": "TV",
        "rating": "R",
        "episodes": "long",
        "mood": "dark",
        "year": "modern",
        "description": "Humanity fights for survival against giant humanoid creatures called Titans.",
        "image_url": "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
    },
    {
        "id": 2,
        "title": "Fullmetal Alchemist: Brotherhood",
        "genre": ["action", "adventure", "drama", "fantasy"],
        "type": "TV",
        "rating": "R",
        "episodes": "long",
        "mood": "mixed",
        "year": "modern",
        "description": "Two brothers use alchemy to search for the Philosopher's Stone after a failed attempt to resurrect their mother.",
        "image_url": "https://cdn.myanimelist.net/images/anime/1223/96541.jpg",
    },
    {
        "id": 3,
        "title": "Your Lie in April",
        "genre": ["romance", "drama", "music", "slice-of-life"],
        "type": "TV",
        "rating": "PG-13",
        "episodes": "medium",
        "mood": "mixed",
        "year": "modern",
        "description": "A piano prodigy rediscovers his love for music through a free-spirited violinist.",
        "image_url": "https://cdn.myanimelist.net/images/anime/3/67177.jpg",
    },
    {
        "id": 4,
        "title": "One Punch Man",
        "genre": ["action", "comedy", "sci-fi", "superhero"],
        "type": "TV",
        "rating": "R",
        "episodes": "short",
        "mood": "light",
        "year": "modern",
        "description": "A superhero who can defeat any enemy with a single punch seeks a worthy opponent.",
        "image_url": "https://cdn.myanimelist.net/images/anime/12/76049.jpg",
    },
    {
        "id": 5,
        "title": "Spirited Away",
        "genre": ["adventure", "fantasy", "supernatural"],
        "type": "Movie",
        "rating": "PG",
        "episodes": "short",
        "mood": "mixed",
        "year": "classic",
        "description": "A young girl gets trapped in a mysterious spirit world and must find a way to free herself and her parents.",
        "image_url": "https://cdn.myanimelist.net/images/anime/6/79597.jpg",
    },
    {
        "id": 6,
        "title": "Naruto",
        "genre": ["action", "adventure", "comedy", "supernatural"],
        "type": "TV",
        "rating": "PG-13",
        "episodes": "long",
        "mood": "mixed",
        "year": "classic",
        "description": "A young ninja with dreams of becoming the strongest ninja and leader of his village.",
        "image_url": "https://cdn.myanimelist.net/images/anime/13/17405.jpg",
    },
    {
        "id": 7,
        "title": "Clannad: After Story",
        "genre": ["romance", "drama", "slice-of-life"],
        "type": "TV",
        "rating": "PG-13",
        "episodes": "medium",
        "mood": "dark",
        "year": "classic",
        "description": "A continuation of Clannad following Tomoya and Nagisa's life after high school.",
        "image_url": "https://cdn.myanimelist.net/images/anime/1804/95033.jpg",
    },
    {
        "id": 8,
        "title": "Sword Art Online",
        "genre": ["action", "adventure", "romance", "fantasy", "sci-fi"],
        "type": "TV",
        "rating": "PG-13",
        "episodes": "long",
        "mood": "mixed",
        "year": "modern",
        "description": "Players are trapped in a virtual reality MMORPG and must clear the game to escape.",
        "image_url": "https://cdn.myanimelist.net/images/anime/11/39717.jpg",
    },
    {
        "id": 9,
        "title": "Death Note",
        "genre": ["mystery", "supernatural", "psychological", "drama"],
        "type": "TV",
        "rating": "R",
        "episodes": "medium",
        "mood": "dark",
        "year": "classic",
        "description": "A high school student discovers a supernatural notebook that allows him to kill anyone by writing their name.",
        "image_url": "https://cdn.myanimelist.net/images/anime/9/9453.jpg",
    },
    {
        "id": 10,
        "title": "My Neighbor Totoro",
        "genre": ["fantasy", "slice-of-life", "adventure"],
        "type": "Movie",
        "rating": "G",
        "episodes": "short",
        "mood": "light",
        "year": "classic",
        "description": "Two young sisters and their father encounter friendly forest spirits while moving to the countryside.",
        "image_url": "https://cdn.myanimelist.net/images/anime/4/75923.jpg",
    },
    {
        "id": 11,
        "title": "Hunter x Hunter (2011)",
        "genre": ["action", "adventure", "fantasy"],
        "type": "TV",
        "rating": "PG-13",
        "episodes": "long",
        "mood": "mixed",
        "year": "modern",
        "description": "A young boy follows his father's footsteps to become a Hunter, a licensed professional who undertakes dangerous tasks.",
        "image_url": "https://cdn.myanimelist.net/images/anime/1337/99013.jpg",
    },
    {
        "id": 12,
        "title": "Demon Slayer",
        "genre": ["action", "adventure", "supernatural", "drama"],
        "type": "TV",
        "rating": "R",
        "episodes": "medium",
        "mood": "dark",
        "year": "recent",
        "description": "A young boy becomes a demon slayer after his family is slaughtered and his sister is turned into a demon.",
        "image_url": "https://cdn.myanimelist.net/images/anime/1286/99889.jpg",
    },
    {
        "id": 13,
        "title": "Steins;Gate",
        "genre": ["sci-fi", "mystery", "drama", "thriller"],
        "type": "TV",
        "rating": "PG-13",
        "episodes": "medium",
        "mood": "dark",
        "year": "modern",
        "description": "A self-proclaimed mad scientist discovers time travel and must prevent a dystopian future.",
        "image_url": "https://cdn.myanimelist.net/images/anime/5/73199.jpg",
    },
    {
        "id": 14,
        "title": "Re:Zero",
        "genre": ["fantasy", "drama", "psychological", "action"],
        "type": "TV",
        "rating": "R",
        "episodes": "long",
        "mood": "dark",
        "year": "modern",
        "description": "A young man is transported to a fantasy world and discovers he has the ability to rewind time upon death.",
        "image_url": "https://cdn.myanimelist.net/images/anime/1522/128039.jpg",
    },
    {
        "id": 15,
        "title": "Haikyuu!!",
        "genre": ["sports", "comedy", "drama"],
        "type": "TV",
        "rating": "PG-13",
        "episodes": "long",
        "mood": "light",
        "year": "modern",
        "description": "A high school student strives to become a top volleyball player despite his short stature.",
        "image_url": "https://cdn.myanimelist.net/images/anime/7/76014.jpg",
    },
    {
        "id": 16,
        "title": "Violet Evergarden",
        "genre": ["drama", "fantasy", "slice-of-life"],
        "type": "TV",
        "rating": "PG-13",
        "episodes": "medium",
        "mood": "mixed",
        "year": "recent",
        "description": "A former soldier becomes an Auto Memory Doll to understand the meaning of 'I love you'.",
        "image_url": "https://cdn.myanimelist.net/images/anime/1795/95088.jpg",
    },
    {
        "id": 17,
        "title": "Cowboy Bebop",
        "genre": ["action", "adventure", "sci-fi", "comedy", "drama"],
        "type": "TV",
        "rating": "R",
        "episodes": "medium",
        "mood": "mixed",
        "year": "classic",
        "description": "A crew of bounty hunters travel the solar system chasing criminals while dealing with their past.",
        "image_url": "https://cdn.myanimelist.net/images/anime/4/19644.jpg",
    },
    {
        "id": 18,
        "title": "Neon Genesis Evangelion",
        "genre": ["action", "sci-fi", "drama", "psychological"],
        "type": "TV",
        "rating": "PG-13",
        "episodes": "medium",
        "mood": "dark",
        "year": "classic",
        "description": "Teenagers pilot giant mecha to defend Earth from mysterious beings called Angels.",
        "image_url": "https://cdn.myanimelist.net/images/anime/1935/127974.jpg",
    },
    {
        "id": 19,
        "title": "Toradora!",
        "genre": ["romance", "comedy", "slice-of-life", "drama"],
        "type": "TV",
        "rating": "PG-13",
        "episodes": "medium",
        "mood": "light",
        "year": "classic",
        "description": "Two high school students team up to help each other get together with their respective crushes.",
        "image_url": "https://cdn.myanimelist.net/images/anime/13/22128.jpg",
    },
    {
        "id": 20,
        "title": "Dragon Ball Z",
        "genre": ["action", "adventure", "comedy", "fantasy"],
        "type": "TV",
        "rating": "PG-13",
        "episodes": "long",
        "mood": "mixed",
        "year": "classic",
        "description": "Goku and his allies defend Earth against increasingly powerful enemies.",
        "image_url": "https://cdn.myanimelist.net/images/anime/1277/142971.jpg",
    },
    {
        "id": 21,
        "title": "Jujutsu Kaisen",
        "genre": ["action", "supernatural", "drama", "horror"],
        "type": "TV",
        "rating": "R",
        "episodes": "medium",
        "mood": "dark",
        "year": "recent",
        "description": "A high school student swallows a cursed object and joins a secret organization of Jujutsu Sorcerers.",
        "image_url": "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
    },
    {
        "id": 22,
        "title": "Kimi no Na wa (Your Name)",
        "genre": ["romance", "drama", "fantasy", "supernatural"],
        "type": "Movie",
        "rating": "PG",
        "episodes": "short",
        "mood": "mixed",
        "year": "recent",
        "description": "Two strangers find themselves linked in a bizarre way as they swap bodies and search for each other.",
        "image_url": "https://cdn.myanimelist.net/images/anime/5/87048.jpg",
    },
    {
        "id": 23,
        "title": "A Silent Voice",
        "genre": ["drama", "romance", "slice-of-life"],
        "type": "Movie",
        "rating": "PG-13",
        "episodes": "short",
        "mood": "dark",
        "year": "recent",
        "description": "A former bully seeks forgiveness from a deaf girl he tormented in elementary school.",
        "image_url": "https://cdn.myanimelist.net/images/anime/1122/96435.jpg",
    },
    {
        "id": 24,
        "title": "One Piece",
        "genre": ["action", "adventure", "comedy", "fantasy"],
        "type": "TV",
        "rating": "PG-13",
        "episodes": "long",
        "mood": "mixed",
        "year": "classic",
        "description": "A young pirate with a rubber body searches for the world's ultimate treasure, the 'One Piece'.",
        "image_url": "https://cdn.myanimelist.net/images/anime/6/73245.jpg",
    },
    {
        "id": 25,
        "title": "No Game No Life",
        "genre": ["comedy", "fantasy", "adventure", "sci-fi"],
        "type": "TV",
        "rating": "PG-13",
        "episodes": "short",
        "mood": "light",
        "year": "modern",
        "description": "Genius siblings are summoned to a fantasy world where everything is decided by games.",
        "image_url": "https://cdn.myanimelist.net/images/anime/1074/111944.jpg",
    },
]

# Rules for the inference engine.
# Each rule maps a set of user preference conditions to a weight boost for matching anime.
# Structure: {"conditions": {attr: value_or_list}, "boost": float, "reason": str}
RULES = [
    {
        "conditions": {"preferred_genre": "action", "preferred_mood": "dark"},
        "boost": 3.0,
        "reason": "You like dark action stories",
    },
    {
        "conditions": {"preferred_genre": "action", "preferred_mood": "light"},
        "boost": 2.5,
        "reason": "You like light-hearted action",
    },
    {
        "conditions": {"preferred_genre": "romance", "preferred_mood": "mixed"},
        "boost": 2.5,
        "reason": "You enjoy bittersweet romance",
    },
    {
        "conditions": {"preferred_genre": "romance", "preferred_mood": "dark"},
        "boost": 2.0,
        "reason": "You prefer emotional, dramatic romance",
    },
    {
        "conditions": {"preferred_genre": "romance", "preferred_mood": "light"},
        "boost": 2.5,
        "reason": "You enjoy lighthearted romance",
    },
    {
        "conditions": {"preferred_genre": "fantasy", "preferred_type": "Movie"},
        "boost": 2.5,
        "reason": "You love fantasy movies",
    },
    {
        "conditions": {"preferred_genre": "sci-fi", "preferred_mood": "dark"},
        "boost": 2.5,
        "reason": "You enjoy dark sci-fi themes",
    },
    {
        "conditions": {"preferred_genre": "mystery", "preferred_mood": "dark"},
        "boost": 3.0,
        "reason": "You love dark mystery/thriller stories",
    },
    {
        "conditions": {"preferred_genre": "sports", "preferred_mood": "light"},
        "boost": 3.0,
        "reason": "You enjoy uplifting sports anime",
    },
    {
        "conditions": {"preferred_genre": "slice-of-life", "preferred_mood": "light"},
        "boost": 2.5,
        "reason": "You enjoy calm, everyday stories",
    },
    {
        "conditions": {"preferred_genre": "comedy", "preferred_mood": "light"},
        "boost": 2.5,
        "reason": "You enjoy lighthearted comedies",
    },
    {
        "conditions": {"preferred_genre": "supernatural", "preferred_mood": "dark"},
        "boost": 2.5,
        "reason": "You like dark supernatural stories",
    },
    {
        "conditions": {"preferred_type": "Movie", "preferred_episodes": "short"},
        "boost": 2.0,
        "reason": "You prefer short, complete movie experiences",
    },
    {
        "conditions": {"preferred_type": "TV", "preferred_episodes": "long"},
        "boost": 2.0,
        "reason": "You enjoy following long series",
    },
    {
        "conditions": {"preferred_year": "classic"},
        "boost": 1.5,
        "reason": "You appreciate classic anime",
    },
    {
        "conditions": {"preferred_year": "recent"},
        "boost": 1.5,
        "reason": "You enjoy recent anime",
    },
    {
        "conditions": {"preferred_genre": "drama", "preferred_mood": "dark"},
        "boost": 2.0,
        "reason": "You enjoy heavy emotional dramas",
    },
    {
        "conditions": {"preferred_genre": "adventure", "preferred_episodes": "long"},
        "boost": 2.0,
        "reason": "You love long adventure journeys",
    },
    {
        "conditions": {"preferred_genre": "psychological"},
        "boost": 2.0,
        "reason": "You enjoy mind-bending psychological stories",
    },
    {
        "conditions": {"preferred_genre": "horror", "preferred_mood": "dark"},
        "boost": 3.0,
        "reason": "You enjoy dark horror/supernatural content",
    },
]

# Questions to ask the user (questionnaire)
QUESTIONS = [
    {
        "id": "preferred_genre",
        "text": "What is your favorite anime genre?",
        "options": [
            ("action", "Action / Fighting"),
            ("adventure", "Adventure / Exploration"),
            ("romance", "Romance / Love Story"),
            ("comedy", "Comedy / Humor"),
            ("drama", "Drama / Emotional"),
            ("fantasy", "Fantasy / Magic"),
            ("sci-fi", "Sci-Fi / Futuristic"),
            ("mystery", "Mystery / Thriller"),
            ("supernatural", "Supernatural / Paranormal"),
            ("horror", "Horror / Dark"),
            ("sports", "Sports"),
            ("slice-of-life", "Slice of Life / Everyday"),
            ("psychological", "Psychological / Mind Games"),
        ],
    },
    {
        "id": "preferred_mood",
        "text": "What kind of overall mood do you prefer?",
        "options": [
            ("dark", "Dark / Intense / Serious"),
            ("light", "Light / Fun / Cheerful"),
            ("mixed", "Mixed / Balanced (both dark and light)"),
        ],
    },
    {
        "id": "preferred_type",
        "text": "Do you prefer TV series or movies?",
        "options": [
            ("TV", "TV Series"),
            ("Movie", "Movie"),
            ("any", "No preference"),
        ],
    },
    {
        "id": "preferred_episodes",
        "text": "How long do you want the series to be?",
        "options": [
            ("short", "Short (1–13 episodes / single movie)"),
            ("medium", "Medium (14–50 episodes)"),
            ("long", "Long (50+ episodes)"),
            ("any", "No preference"),
        ],
    },
    {
        "id": "preferred_year",
        "text": "Do you have an era preference?",
        "options": [
            ("classic", "Classic (before 2010)"),
            ("modern", "Modern (2010–2018)"),
            ("recent", "Recent (2019–present)"),
            ("any", "No preference"),
        ],
    },
]
